apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dwi-wa
  name: dwi-wa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dwi-wa
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: dwi-wa
    spec:
      containers:
      - env:
        - name: CONF_SRV
          value: config-server
        - name: IMAGE_STORE_PATH
          value: /temp/images/imagesUpload
        - name: NMING_SVR
          value: naming-server
        - name: RB_PSW
          value: guest
        - name: RB_PT
          value: "5672"
        - name: RB_SRV
          value: rabbitmq
        - name: RB_USR
          value: guest
        image: tosaporn/dwi-frontend:0.0.6-SNAPSHOT
        imagePullPolicy: Always
        name: dwi-wa
        volumeMounts:
        - mountPath: /tmp/images/
          name: image-dwi
      restartPolicy: Always
      volumes:
      - name: image-dwi
        persistentVolumeClaim:
          claimName: image-dwi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dwi-wa
  name: dwi-wa
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    io.kompose.service: dwi-wa
  sessionAffinity: None #CHANGE
  type: NodePort
