spring:
  application:
    name: dwi-ws  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:IVRDB}
    username: ${DB_USERNAME:ivrad}
    password: ${DB_PASSWORD:tosaporn}    hikari:      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  http:
      log-request-details: true
  servlet:    multipart:      enabled: true
      max-file-size: 10MB      max-request-size: 10MB  rabbitmq:    host: ${RB_SRV:localhost}
    username: ${RB_USR:guest}
    password: ${RB_PSW:guest}
    port: ${RB_PT:5672}
server:  port: 8100
logging:  level:    org.springframework: info
    th.co.acc.dwi.repository: info
    com.spring.ibatis.UserMapper: info
    org.mybatis.spring: info

eureka:  client:    service-url:      defaultZone: http://${NMING_SVR:localhost}:8761/eureka/    fetch-registry: true
    register-with-eureka: true
  instance:    hostname: dwi-ws
    prefer-ip-address: true
    
management:  endpoints:    web:      exposure:        include: '*'
  endpoint:    health:      show-details: always 